### ISSUE TITLE
How to save the "tree" in Vaa-3D

### ISSUE THREAD

**Issue by hnuwangchao** [lsqshr/Rivulet-Neuron-Tracing-Toolbox#19]
Dear profession
In your code ,the "tree" is a matrix，I want use the “ tree” get a 3D graphics inVaa-3D

**Comment by donghaozhang** [comment]
You can use saveswc function in utli folder.

**Comment by donghaozhang** [comment]
Typo: utli-> util

**Comment by hnuwangchao** [comment]
yes  ,I want use the saveswc function but I  don't find your code in  utli folder.




------------------ 原始邮件 ------------------
发件人: "donghaozhang";<notifications@github.com>;
发送时间: 2017年9月18日(星期一) 下午4:21
收件人: "RivuletStudio/Rivulet-Neuron-Tracing-Toolbox"<Rivulet-Neuron-Tracing-Toolbox@noreply.github.com>;
抄送: "愚者在路上"<767672528@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [RivuletStudio/Rivulet-Neuron-Tracing-Toolbox] How to save the"tree" in Vaa-3D (#19)




You can use saveswc function in utli folder.

**Comment by donghaozhang** [comment]
function saveswc( swc, outfilename )
%SAVESWC Summary of this function goes here
%   Detailed explanation goes here

if isempty(swc),
    return;
end

if size(swc,2)<7,
    error('The first variable must have at least 7 columns.'),
end

f = fopen(outfilename, 'wt');
if f<=0,
    error('Fail to open file to write');
end

for i=1:size(swc,1),
    fprintf(f, '%d %d %5.3f %5.3f %5.3f %5.3f %d\n',...
        swc(i,1), swc(i,2), swc(i,3), swc(i,4), swc(i,5), swc(i,6), swc(i,7));
end

fclose(f);

end

**Comment by hnuwangchao** [comment]
oh,thanks very much.
I think you are a great man ,love you!




------------------ 原始邮件 ------------------
发件人: "donghaozhang";<notifications@github.com>;
发送时间: 2017年9月18日(星期一) 下午4:30
收件人: "RivuletStudio/Rivulet-Neuron-Tracing-Toolbox"<Rivulet-Neuron-Tracing-Toolbox@noreply.github.com>;
抄送: "愚者在路上"<767672528@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [RivuletStudio/Rivulet-Neuron-Tracing-Toolbox] How to save the"tree" in Vaa-3D (#19)




function saveswc( swc, outfilename )
 %SAVESWC Summary of this function goes here
 %   Detailed explanation goes here
 
if isempty(swc),
 return;
 end
 
if size(swc,2)<7,
 error('The first variable must have at least 7 columns.'),
 end
 
f = fopen(outfilename, 'wt');
 if f<=0,
 error('Fail to open file to write');
 end
 
for i=1:size(swc,1),
 fprintf(f, '%d %d %5.3f %5.3f %5.3f %5.3f %d\n',...
 swc(i,1), swc(i,2), swc(i,3), swc(i,4), swc(i,5), swc(i,6), swc(i,7));
 end
 
fclose(f);
 
end

**Comment by hnuwangchao** [comment]
Dear donghao
Do you have the code of APP2 which can run well in Matlab 2014 or 2015. 




------------------ 原始邮件 ------------------
发件人: "donghaozhang";<notifications@github.com>;
发送时间: 2017年9月18日(星期一) 下午4:30
收件人: "RivuletStudio/Rivulet-Neuron-Tracing-Toolbox"<Rivulet-Neuron-Tracing-Toolbox@noreply.github.com>;
抄送: "愚者在路上"<767672528@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [RivuletStudio/Rivulet-Neuron-Tracing-Toolbox] How to save the"tree" in Vaa-3D (#19)




function saveswc( swc, outfilename )
 %SAVESWC Summary of this function goes here
 %   Detailed explanation goes here
 
if isempty(swc),
 return;
 end
 
if size(swc,2)<7,
 error('The first variable must have at least 7 columns.'),
 end
 
f = fopen(outfilename, 'wt');
 if f<=0,
 error('Fail to open file to write');
 end
 
for i=1:size(swc,1),
 fprintf(f, '%d %d %5.3f %5.3f %5.3f %5.3f %d\n',...
 swc(i,1), swc(i,2), swc(i,3), swc(i,4), swc(i,5), swc(i,6), swc(i,7));
 end
 
fclose(f);
 
end
