### ISSUE TITLE
code of app2

### ISSUE THREAD

**Issue by hnuwangchao** [lsqshr/Rivulet-Neuron-Tracing-Toolbox#20]
Dear donghao
Do you have the code of APP2 which can run well in Matlab 2014 or 2015.

**Comment by donghaozhang** [comment]
I personally know the author of APP2 and I think he told the matlab version of APP2 is already lost(You can double check). You can use bash file to run APP2 using Vaa3D. command-line: v3d -x vn2 -f app2 -i FILE1 -o FILE2 -p NULL 0 0 0 1 1 1 4 0 0 0(similar to this one).

**Comment by hnuwangchao** [comment]
Dear donghao
Thank you very much for your reply，I also have a problem ,I have your code of matlab,i think that i change code of matlab to code of C++ is large task。Do you have the code of C++ which can run in V3d.

**Comment by donghaozhang** [comment]
The following link is c++ version of Rivulet2 (https://www.biorxiv.org/content/biorxiv/early/2017/02/20/109892.full.pdf) rather Rivulet1. https://github.com/Vaa3D/vaa3d_tools/tree/master/released_plugins/v3d_plugins/bigneuron_siqi_rivuletv3d

**Comment by hnuwangchao** [comment]
Oh ,I can not  how to describe my feelings at the moment.If People around the world can be like you, how wonderful the world will be。
