### ISSUE TITLE
Time Complexity of your paper

### ISSUE THREAD

**Issue by hnuwangchao** [lsqshr/Rivulet-Neuron-Tracing-Toolbox#22]
Dear Donghao
I try to use  your code of C++ run inVaa3D,since I would like to compare your algorithm and APP2 speed on Vaa3D。In fact ,i am fail . Can you tell  how to prove your algorithm are faster than APP2.

**Comment by lsqshr** [comment]
We never claimed that Rivulet was faster than APP2 in any of our paper. It is slower than APP2 but It just works.
