### ISSUE TITLE
How is the result of SD and SSD calculated?

### ISSUE THREAD

**Issue by hnuwangchao** [lsqshr/Rivulet-Neuron-Tracing-Toolbox#23]
Dear Donghao 
How is the result of SD and SSD calculated?

**Comment by donghaozhang** [comment]
@hnuwangchao Siqi agrees to share his latest python SD SSD code with you. @lsqshr Thanks for the help.

**Comment by hnuwangchao** [comment]
Dear Donhghao 
I try to write the SD code in matlab,does my code match the meaning of your SD? 


clear all;
Location=load( 'D:\transform x_y 1\OP_9_stand.swc');
goldloaction=Location(:,3:5);
somaLocation1=load( 'D:\wang_chao_resource\OP\OP_9_stack.tif_MOST.swc');
otherloaction1=somaLocation1(:,3:5);
distancevector=[];
for i=1:length(goldloaction)
     minidistance=200;
    for j=1:length(otherloaction1)
        distance=sqrt((goldloaction(i,1)-otherloaction1(j,1))^2+(goldloaction(i,2)-otherloaction1(j,2))^2+(goldloaction(i,3)-otherloaction1(j,3))^2);
        if distance<minidistance
            minidistance=distance;
        end
    end
  distancevector(i)=minidistance;
end
sum=0;
for h=1:i
    sum=sum+distancevector(h);
end
newdistance=sum/i;

**Comment by lsqshr** [comment]
@donghaozhang I ll organise my code a bit and directly merge them into rivuletpy

**Comment by donghaozhang** [comment]
@lsqshr thank you so much for the help.

**Comment by lsqshr** [comment]
The evaluation code used in rivuletpy can be found at https://github.com/RivuletStudio/rivuletpy/blob/master/rivuletpy/utils/metrics.py
under 
`def precision_recall(swc1, swc2, dist1=4, dist2=4):`
